### ISSUE TITLE
Is this SDK still being supported?

### ISSUE THREAD

**Issue by adomanico** [venmo/venmo-ios-sdk#101]
I see that the latest version of the SDK is dated to over a year ago. 

Having issues integrating the SDK into our XCode 7 project with cocoapods 0.38.2 (a slew of linker errors as seen in this issue https://github.com/venmo/venmo-ios-sdk/issues/89)

Are there any plans for an update?

**Comment by btrzupek** [comment]
see #100 as well. It appears that the SDK is pretty out of sync with what the server is responding with as well.

**Comment by eliperkins** [comment]
We definitely hear you. The state of this SDK is unacceptable and we definitely want to get this cleaned up. We'll spend time soon to get this to a better place, along with a new version of the SDK that we've been planning. Expect to hear more from us by the end of the week.

**Comment by btrzupek** [comment]
Thanks so much for the update!
