### ISSUE TITLE
iOS SDK work for tvOS?

### ISSUE THREAD

**Issue by jeremybrowning** [venmo/venmo-ios-sdk#114]
Hi Venmo Team!

Firstly, I love using Venmo. 

I'm curious if you can confirm whether the iOS SDK is functional if used inside of a tvOS app? Theoretically, the SDK could provide a secure way for users to send money directly from a tvOS app via Venmo.

**Comment by dasmer** [comment]
HI Jeremy,

Glad you love Venmo! While the SDK does not officially support tvOS yet (though you are welcome to try and make tweaks), we do plan on releasing an SDK with tvOS support sometime in the future.
