### ISSUE TITLE
Is there a Swift version?

### ISSUE THREAD

**Issue by DRR11** [venmo/venmo-ios-sdk#119]
Hi everyone. 

I am new to iOS programming and I am solely using Swift2. So, I am not familiar with Objective C at all. I've been successfully translated objective c code to swift for some other easier APIs. But I am having some trouble on this. Could someone who have implemented this using Swift2 provide a guide for this? I will really appreciate!! :D

Thank you!

**Comment by eliperkins** [comment]
There is currently a more Swift friendly version being planned, but this SDK will remain our official SDK for some time. Others have integrated with this SDK in Swift, you can see #63, #64 and a variety of other issues on this repo to learn how others have integrated.
