### ISSUE TITLE
Testing in Another Country

### ISSUE THREAD

**Issue by ghost** [venmo/venmo-ios-sdk#134]
Hello Team, 
I am developing an iPhone application with integrating payment method brain-tree venmo. I am facing some issue regarding show venmo icon in drop in. I know the venmo is not available in India. Please let me know any alternative way to check integration or doing test payment in India.
Looking forward to hear from you.
Thanks & Regards
Sham Dhiman

**Comment by chetan-duke** [comment]
Any update on this? Looking same here...

**Comment by ghost** [comment]
No @chetan-duke
