### ISSUE TITLE
Url escaped strings show up after app switch

### ISSUE THREAD

**Issue by sschiffli** [venmo/venmo-ios-sdk#48]
Calling the sendPaymentTo: amount: note: function mangles the strings when they show up in the app switch.
![img_0010](https://cloud.githubusercontent.com/assets/1711485/4468812/17aa1b58-4905-11e4-951e-a5b95a34883b.PNG)

**Comment by eliperkins** [comment]
Closing this as it has been addressed in the current App Store version (if not prior to).
