### ISSUE TITLE
Tutorial in Swift

### ISSUE THREAD

**Issue by cassidoo** [venmo/venmo-ios-sdk#55]
Several people requested some advice on getting the SDK to work with Swift, for a tutorial on it somewhere here in this repo.

**Comment by ayanonagon** [comment]
I’m away from my computer right now but this is what they need to read: https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

Main key is the bridging header!

**Comment by cassidoo** [comment]
Awesome!  Never mind then. :)
