### ISSUE TITLE
Authorize App hanging

### ISSUE THREAD

**Issue by KathleenFMalone** [venmo/venmo-ios-sdk#56]
When I call requestPermissions method in my app I am transferred to my venmo app "Authorize App" view. But when I click on the Authorize or Deny button nothing happens. Venmo just hangs there.

This is the code I use in my app:
  [[Venmo sharedInstance] requestPermissions:@[VENPermissionMakePayments,
                                                 VENPermissionAccessProfile]
                         withCompletionHandler:^(BOOL success, NSError *error) {
                             if (success) {
                                 // :)
                                 NSLog(@"permission granted");
                             }
                             else {
                                 // :(
                                 NSLog(@"permission not granted");
                             }
                         }];

**Comment by eliperkins** [comment]
Have you followed the [setup steps mentioned in the README](https://github.com/venmo/venmo-ios-sdk#3-initialize-the-venmo-ios-sdk)? It sounds like Venmo is trying to redirect back to your app, but your app isn't listening.

**Comment by KathleenFMalone** [comment]
Sorry, just saw I had a typo in the URL Schemes. All good now. Thanks for following up!

**Comment by eliperkins** [comment]
No worries! Glad you figured it out!
