### ISSUE TITLE
Minivenmo build issue

### ISSUE THREAD

**Issue by jhu724** [venmo/venmo-ios-sdk#57]
When I run "pod install" in the "sample" directory, I get the following error message:

[!] Unable to satisfy the following requirements:

- `Venmo-iOS-SDK (from `..`)` required by `Podfile`
- `Venmo-iOS-SDK (= 1.1.0)` required by `Podfile.lock`

Please help, thanks.

**Comment by dasmer** [comment]
@jhu724 Just merged a fix. You should be good to go with ```pod install``` now :octocat:

**Comment by jhu724** [comment]
@dasmer I'm still getting the same error. After cloning, I ran 'pod install' in the parent 'venmo-ios-sdk' directory, then again in 'sample'. Thanks.

**Comment by dasmer** [comment]
@jhu724 Are you sure you're using the a new clone? I replicated your steps and ```pod install``` worked successfully.  
Just to be sure, run this script which runs through all of the steps:
```
rm -rf venmo-ios-sdk && git clone git@github.com:venmo/venmo-ios-sdk.git && cd venmo-ios-sdk && pod install && cd sample && pod install
```

**Comment by jhu724** [comment]
I wasn't using the new clone. Thanks!
