### ISSUE TITLE
Swift support for venmo API calls.

### ISSUE THREAD

**Issue by sudov** [venmo/venmo-ios-sdk#59]
Hi there,
I'm trying to figure out how to initialize the sdk at the stage where i add: 
[Venmo startWithAppId:"VENMO_APP_ID" secret:"VENMO_APP_SECRET" name:"VENMO_APP_NAME"]

to the delegate. I think i can convert the rest of the obj-C. I have the import sdk.h thing in a bridging header (had to do this for fb too so..) so would really appreciate help!

Best,
Vinay.

**Comment by sudov** [comment]
Hi there,
Ignore the above request. Figured it out - sorry for the bother.

Best,
Vinay.

**Comment by eliperkins** [comment]
Glad you figured things out! Feel free to share your solution here for others as well.

**Comment by sudov** [comment]
The issue was really me not knowing swift. Here is the swift variant of what you have in the setup guide.

Venmo.startWithAppId("app_id", secret:"your_secret", name:"app_name")
