### ISSUE TITLE
'Venmo-iOS-SDK/Venmo.h' file not found

### ISSUE THREAD

**Issue by sudov** [venmo/venmo-ios-sdk#60]
Im setting up venmo integration for my app with cocoapods and have an issue that doesn't seem to have a fix online.

So I have a bridging header file, the code for which is below:
#ifndef SplitPea_Bridge_Header_h
#define SplitPea_Bridge_Header_h

#import FacebookSDK/FacebookSDK.h
#import Venmo-iOS-SDK/Venmo.h
(Ignore the absence of < and > above, github was being weird)
#endif

and get an error that reads 'Venmo-iOS-SDK/Venmo.h' file not found'

Now i know the .h file is accessible because when i do Cmd+click on keyword Venmo.something in the AppDelegate it routes me to the .h file but when compiling I get the above error.

Help!

**Comment by sudov** [comment]
So turns out this is a cocoapods issue. version 0.036 is the one that supports swift and has to be obtained separately for a swift app to work.

Note, you have to remove all the Pod stuff from your folder and .xcworkspace directory for this to work. Following this you can just "pod init" and redo the pod setup process.

"MAKE SURE YOU SAVE YOUR PODFILE SOMEPLACE BEFORE YOU REMOVE THE OLD POD files/folders"

**Comment by Tedko** [comment]
I found the same issue, my pod ver is 0.39.0
