### ISSUE TITLE
sendPaymentTo() Swift "Extra Argument 'audience' in call

### ISSUE THREAD

**Issue by jsanders67** [venmo/venmo-ios-sdk#64]
I keep getting a compile Error in Xcode: Extra Argument 'Audience' in call
when I try to call my sendPaymentTo() method. Below is the code I have written

```swift
var audienceType = VENTransactionAudience.Private
Venmo.sharedInstance().sendPaymentTo(self.name?.text, amount: self.amount?.text.toInt(), note: self.note?.text, audience: audienceType, completionHandler: { (transaction,success,error) -> Void in
            if success {
                println("success")
            }
            else
            {
                prinln("Error")
            }
            
})
```
I have tried deleting Audience as a field and it says that I am lacking an argument 'audience' when I do so. I have also tried passing in nil and "private" as parameters for this argument. 

Has anyone else experienced the same problem or recognize my mistake?

**Comment by eliperkins** [comment]
This seems to work fine for me in Xcode 6.3 (after fixing the `prinln` to `println` in the error state). Do you have any more information about the error? Maybe a screenshot or more error logs?

**Comment by jsanders67** [comment]
![image](https://cloud.githubusercontent.com/assets/10730172/6241410/64e058ee-b6ea-11e4-933f-b66f123aa8b9.png)

Thats all Im getting. It does not build.I am on Xcode 6.1.1. Do you think that is the problem?

**Comment by eliperkins** [comment]
Hm. I'd be curious to see if you continue to have issues on Xcode 6.3. If so, we can continue to debug, but with Swift in flux to much, I'm not inclined to make changes to an Obj-C project such as this without fully considering the implications of using our SDK in Swift.

Try Xcode 6.3 for me and let me know if you continue to have these warnings!

**Comment by jsanders67** [comment]
![screenshot 2015-02-18 17 20 23 jpeg](https://cloud.githubusercontent.com/assets/10730172/6258029/3188941c-b793-11e4-86df-f1f284ce9b5c.png)


Yeah I'm continuing to get Errors. Would it possibly be because my amount is an int and not  Uint? Or possibly because they are all optionals?
Sorry to pretty much make you debug my code, but Im wondering as well if this is a swift issue.
Thanks

**Comment by eliperkins** [comment]
I'd say the optionals are the cause of this one. Try unwrapping the optionals and passing them to the `sendPaymentTo` method. Since Obj-C can't handle optionals, I'd say this has probably been the root cause of the initial issue, Xcode 6.3 is just giving you a better error now.

**Comment by jsanders67** [comment]
Unwrapping the optionals worked. I think the problem in the end was also that the toInt() function returns an optional value as well.
For those who run into this same problem:
I converted the string from the text field to a float * 100
converted that value to a int
an converted that value to a UInt


converting straight to an Int will truncate the decimal places so the float value *100 is necessary and I could not find a conversion straight from float to uint so I by passed this by converting from float to int to uint.

**Comment by schan93** [comment]
@jsanders67  I am also having this issue. I have tried to unwrap the optionals with the ! and also tried to listen to your advice to convert the text field to a float * 100 but I can't seem to get it to work. Below is what I have tried: Any advice?

![screen shot 2015-03-24 at 2 21 02 am](https://cloud.githubusercontent.com/assets/1704125/6798637/6a2abee6-d1cc-11e4-93e3-aa064b5c046f.png)

**Comment by jsanders67** [comment]
I believe you need to convert that float value to an Int and then again to a UInt. I'm not totally sure as to why the Venmo SDK uses the UInt, but thats what seemed to work for me. 

 I would also make sure your text fields are not blank by unwrapping all of them before you envoke the sendPayment() request to the Venmo Shared Instance. If one of the text fields is left blank and the IBAction is invoked, a unable to unwrap nil exception will occur at runtime and could cause your app to freeze and lock up in production.

This was my code: (ignore the print statements, makePayment method just invokes the send Payment method with the Transaction Audience being private)


if ((self.name?.text == nil) || (self.amount?.text == nil) || (self.note?.text == nil)) {
            println("Name Field Left Blank \(name?.text == nil)")
            println("Amount Field Left Blank \(amount?.text == nil)")
            println("Note Field Left Blank \(note?.text == nil)")
        }
        else
        {
            println("Envoking make Payment")
            println("\(newAmount)")
            let nonOptional = (newAmount! as NSString).floatValue * 100
            println("\(nonOptional)")
            let intAmount = Int(nonOptional)
            println("int Amount = \(intAmount)")
            let finalAmount = UInt(intAmount)
            makePayment(newName!, newNote: newNote!, newAmount: finalAmount)
        }
}

Not efficient and should be slimmed down, but gets the job done.
