### ISSUE TITLE
The SDK is on v1 but the API has gone up to v3?

### ISSUE THREAD

**Issue by AndrewSB** [venmo/venmo-ios-sdk#66]
I noticed this while trying to get a larger size of the profile picture.
This SDK uses the v1 API, but the venmo website (and API documentation) uses v3. Is this SDK just really out of sync with the rest of the company or is it on v1 for a specific reason?

**Comment by eliperkins** [comment]
v1 is the current version of the Venmo developer API, as seen in [our documentation here](https://developer.venmo.com/docs/endpoints/payments). This SDK, while maintained in sync with the API, may not always map directly to versions of the Venmo developer API. Any changes to the supported Venmo developer API will be handled by changing to a new major version here, to signify a breaking API change.
