### ISSUE TITLE
Is there a way to check the status of a payment via the venmo api?

### ISSUE THREAD

**Issue by sudov** [venmo/venmo-ios-sdk#72]
Well, pretty much ^. I couldn't find a function/ way to get a status.

**Comment by eliperkins** [comment]
Unfortunately, there is no support for checking payment status via the API. You can do so by redirecting users to the Venmo iOS App.

**Comment by sudov** [comment]
Thanks, @eliperkins do you think you could help me figure out why verifying web hooks to my app isn't working? (Or direct me to someplace i can figure it out) I've double checked the response from my server and I'm returning the correct venmo_challenge part of the tuple venmo sends out

**Comment by eliperkins** [comment]
Admittedly, I don't know much about the webhooks. Is your issue related to the webhook never being called? Are they not even called with the `venmo_challenge` parameter? Can you provide any logs from your server related to Venmo's platform requests with this parameter?

**Comment by sudov** [comment]
Absolutely! And thanks for helping. Here is the traffic on my server upon clicking the verify button on the venmo dev admin console thing:

```
<Request 'http://getsplitpea.com:5000/webhook_url?venmo_challenge=jhVbc5B38hbFl19&venmo_challenge=6920f936-b676-4433-a105-413100ddc9db' [GET]>
6920f936-b676-4433-a105-413100ddc9db
184.73.153.40 - - [28/Apr/2015 15:07:17] "GET /webhook_url?venmo_challenge=jhVbc5B38hbFl19&venmo_challenge=6920f936-b676-4433-a105-413100ddc9db HTTP/1.1" 200 -
```

The first is the request as it hits my server, the number beginning 69... is the venmo challenge that needs to be sent back which is exactly what I'm returning (confirmed by the 200 response)

**Comment by sudov** [comment]
This is the screen on the admin console that gets stuck on "Verifying..."
![stuck](https://cloud.githubusercontent.com/assets/4527576/7378069/ce70e990-edb8-11e4-9165-651f41d0b3ea.png)
