### ISSUE TITLE
VENCore.h file missing from zip file

### ISSUE THREAD

**Issue by TaterSalad** [venmo/venmo-ios-sdk#74]
I just downloaded the zip from the venmo-ios-sdk page and my app won't compile because it can't find the VENCore.h file

**Comment by eliperkins** [comment]
You can either use Cocoapods to download this dependency, or download it yourself as a zip here: https://github.com/venmo/vencore

**Comment by TaterSalad** [comment]
Hi Eli, thanks for the help. I downloaded vencore and added it. The vencore readme file claims that this is a separate use for the venmo api and that if you want simple transactions to use the venmo sdk. This was my original plan, but I couldn't use venmo sdk because it wouldn't compile.

Now I'm confronted with about 20 errors in the VENPermissions.h file, one of which is that it cannot find the interface declaration for NSObject. I'm wondering if there is a more fundamental problem here. 

I'm not using cocoapods just downloaded the zip and added it to my project.
