### ISSUE TITLE
Issues getting app id and app secret.

### ISSUE THREAD

**Issue by caraballoj** [venmo/venmo-ios-sdk#84]
Hello, 

I am new to ios development and am running into some issues when trying to implement Venmo to my app. I've downloaded Venno with cocoa pods and am now trying to get the app ID/app secret ID. In my account I try to add a new application, and I get prompted this message "In order to create an application for this account, you must verify your identity. Click here to verify your identity." I then fill in the required information and get an error messag... "Your OAuth token has expired." 

When this happens I refresh the screen and try the process over again with no success. Any help would be appreciated. 

Thanks, 

Jackye

**Comment by cassidoo** [comment]
Hi there Jackye!  This is a common issue, I'm sorry about that.  What's your Venmo username?

**Comment by caraballoj** [comment]
Thank you for getting back to me. Is there a way I can send it to you in private?
