### ISSUE TITLE
Bug in Venmo app: "Pay (null) $1" appears when using this SDK

### ISSUE THREAD

**Issue by rweichler** [venmo/venmo-ios-sdk#85]
A picture speaks a thousand words:

<img src="https://cloud.githubusercontent.com/assets/1661613/8513959/63d43512-2335-11e5-9df6-3a37ceaaa2f7.PNG" height="350"/>

Presumably this is because the app does not query Venmo's servers for the firstname and lastname if you try to initialize a payment using a URL scheme. (notice the dash between Murat and Gursoz, instead of it being "Murat Gursoz")

BTW, the URL scheme I used was:
```
venmosdk://venmo.com?recipients=Murat-Gursoz&txn=pay&note=test
```

I also tried this scheme, with all of the parameters and it also did not work:
```
venmosdk://venmo.com?recipients=Murat-Gursoz&txn=pay&note=test&client=ios&app_name=test&app_id=2734&device_id=&app_version=1.3.0
```

**Comment by rweichler** [comment]
Actually, there's another nasty bug I noticed when using a URL scheme to open the app.

Another one I noticed is when you use a URL scheme to open the app, and you have a passcode/touch ID enabled, it asks for you to enter your passcode or touch ID, but when you do the payment menu is not opened.

**Comment by eliperkins** [comment]
The `(null)` issue should have been resolved by a new version of the Venmo app. We're tracking your second comment via issue #73 for now.

If your first issue still persists, feel free to reopen this issue!
