### ISSUE TITLE
User cannot log in to venmo account via my app

### ISSUE THREAD

**Issue by obazzydave** [venmo/venmo-ios-sdk#90]
So I have successfully installed the venmo sdk on my app and it works fine when I use the Sample app venmo id, but when i use my own venmo app id, the app either crashes or doesn't log the user to his/her venmo account. It keeps coming back to the loggedoutviewcontroller after the "Authorize app" page comes up. Please can you help me out with this. Secondly how can I add like a service charge on every transaction via my app?

**Comment by ayanonagon** [comment]
Dupe to https://github.com/venmo/venmo-ios-sdk/issues/91, closing.
