### ISSUE TITLE
User cannot log in to venmo account via my app

### ISSUE THREAD

**Issue by obazzydave** [venmo/venmo-ios-sdk#91]
So I have successfully installed the venmo sdk on my app and it works fine when I use the Sample app venmo id, but when i use my own venmo app id, the app either crashes or doesn't log the user to his/her venmo account. It keeps coming back to the loggedoutviewcontroller after the "Authorize app" page comes up. Please can you help me out with this. Secondly how can I add like a service charge on every transaction via my app? By the way, is it possible that a wrong web re deirect url can cause this issue

**Comment by ayanonagon** [comment]
1. Can you give us a little more info on the crash? A stack trace would be great.
2. You cannot charge a service charge directly through the Venmo app.

Sorry for the late response. I’m going to close the issue because it’s old, but please feel free to reopen it if it is still an issue. Thanks!
