### ISSUE TITLE
Apple Review rejection for switching to Safari for venmo signin in without app

### ISSUE THREAD

**Issue by nickoneill** [venmo/venmo-ios-sdk#96]
Anyone know if this is a new requirement for Apple? Apparently they want you to open a safari view controller for these things now and *not* switch to the safari app.

**Comment by intelliot** [comment]
Does it seem like Apple won't budge on this, even if you're just using a third-party library that doesn't support SFSafariViewController?

I haven't heard of this as being a *requirement*, but SFSafariViewController is generally a better experience and I imagine it's something we could potentially support here.

**Comment by nickoneill** [comment]
They appealed this decision and were recently approved, so just FYI if someone hits this in the future.
