### ISSUE TITLE
I spent more than a week, yet it still saying my account is not verified.

### ISSUE THREAD

**Issue by yumikohey** [venmo/venmo-ios-sdk#97]
I asked two of my friends, and myself, we've already finished 100% of the checklist. However, it still saying our accounts are not verified, which we can't apply for Venmo's API at all! Cannot get in touch with anyone.

**Comment by adomanico** [comment]
I am also having this issue

**Comment by adomanico** [comment]
phone number verified and email verified and I can not create a developer app

**Comment by eliperkins** [comment]
For any issues revolving around account status, you can contact our Support team on https://help.venmo.com/. They'll be more than happy to resolve any status issues!
